version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: app-flask:1.0.0
    container_name: app-flask
    restart: always
    ports:
      - "5000:5000"
    


